{{- if ne (include "hello-world.namespace" .) .Release.Namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "hello-world.namespace" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
{{- end }}
